{"uuid": "08777d4f-42d2-4dc3-bd31-15d1c255d24c", "children": ["836b9a32-380e-4d8a-8732-7e9b5e89e7a6"], "befores": [{"name": "driver", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_NAME_NOT_RESOLVED\n  (Session info: chrome=127.0.6533.122)\nStacktrace:\n\tGetHandleVerifier [0x00007FF6B5BE9642+30946]\n\t(No symbol) [0x00007FF6B5B9E3D9]\n\t(No symbol) [0x00007FF6B5A96FDA]\n\t(No symbol) [0x00007FF6B5A8F0B5]\n\t(No symbol) [0x00007FF6B5A801E9]\n\t(No symbol) [0x00007FF6B5A81D62]\n\t(No symbol) [0x00007FF6B5A804CE]\n\t(No symbol) [0x00007FF6B5A7FD41]\n\t(No symbol) [0x00007FF6B5A7FC80]\n\t(No symbol) [0x00007FF6B5A7DE84]\n\t(No symbol) [0x00007FF6B5A7E29C]\n\t(No symbol) [0x00007FF6B5A9A041]\n\t(No symbol) [0x00007FF6B5B2BA2E]\n\t(No symbol) [0x00007FF6B5B0CA6A]\n\t(No symbol) [0x00007FF6B5B2B041]\n\t(No symbol) [0x00007FF6B5B0C813]\n\t(No symbol) [0x00007FF6B5ADA6E5]\n\t(No symbol) [0x00007FF6B5ADB021]\n\tGetHandleVerifier [0x00007FF6B5D1F84D+1301229]\n\tGetHandleVerifier [0x00007FF6B5D2BDC7+1351783]\n\tGetHandleVerifier [0x00007FF6B5D22A13+1313971]\n\tGetHandleVerifier [0x00007FF6B5C1DD16+245686]\n\t(No symbol) [0x00007FF6B5BA759F]\n\t(No symbol) [0x00007FF6B5BA3814]\n\t(No symbol) [0x00007FF6B5BA39A2]\n\t(No symbol) [0x00007FF6B5B9A3FF]\n\tBaseThreadInitThunk [0x00007FF99CD355A0+16]\n\tRtlUserThreadStart [0x00007FF99DE4485B+43]\n\n", "trace": "  File \"C:\\Users\\bhuva\\PycharmProjects\\pytest_POM_framework\\.venv\\lib\\site-packages\\pluggy\\_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"C:\\Users\\bhuva\\PycharmProjects\\pytest_POM_framework\\.venv\\lib\\site-packages\\_pytest\\setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n  File \"C:\\Users\\bhuva\\PycharmProjects\\pytest_POM_framework\\.venv\\lib\\site-packages\\pluggy\\_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\Users\\bhuva\\PycharmProjects\\pytest_POM_framework\\.venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 1139, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"C:\\Users\\bhuva\\PycharmProjects\\pytest_POM_framework\\.venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 890, in call_fixture_func\n    fixture_result = next(generator)\n  File \"C:\\Users\\bhuva\\PycharmProjects\\pytest_POM_framework\\demowebshop\\Tests\\conftest.py\", line 8, in driver\n    driver.get(\"https://demowebshop.tricentis.com/\")\n  File \"C:\\Users\\bhuva\\PycharmProjects\\pytest_POM_framework\\.venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 363, in get\n    self.execute(Command.GET, {\"url\": url})\n  File \"C:\\Users\\bhuva\\PycharmProjects\\pytest_POM_framework\\.venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 354, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\Users\\bhuva\\PycharmProjects\\pytest_POM_framework\\.venv\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1724842490616, "stop": 1724842516627}], "start": 1724842490616, "stop": 1724842516698}